name: "Check with oranc"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        system: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.system }}
    permissions:
      contents: read
      packages: write
    services:
      oranc:
        image: ghcr.io/linyinfeng/oranc
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install nix
        uses: cachix/install-nix-action@master
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Setup oranc
        uses: linyinfeng/oranc-action@main
        with:
          orancServerContainer: "${{ job.services.oranc.id }}"
          signingKey: "${{ secrets.ORANC_SIGNING_KEY }}"
      - name: Nix flake check
        run: nix flake check
